name: Compile

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Recurse submodules
      - run: git submodule update --init --recursive

      - name: Install dependencies
        run: sudo apt install nasm libfuse-dev

      - name: Setup build environment
        run: sudo make setup

      - name: Build
        run: make
